#! /bin/sh

#important bsp stuff
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

#bspc config border_width         0
#bspc config window_gap          10

#bspc config split_ratio          0.52
#bspc config focus_follows_pointer 	true
#bspc config pointer_follows_focus 	true

# Truncate a couple of common commands that are used herein.
_bc() {
	bspc config "$@"
}

#### BSPWM configuration ####
_bc window_gap 			  						8
_bc top_padding 									26
_bc top_monocle_padding 					0
_bc border_width 								  5
_bc bottom_padding                5
_bc left_padding                  5
_bc right_padding 								5
_bc single_monocle                false
_bc click_to_focus                false
_bc split_ratio                   0.50
_bc borderless_monocle            true
_bc gapless_monocle               true
_bc focus_by_distance             true
_bc paddingless_monocle  	  			true
_bc focus_follows_pointer         true
_bc ignore_ewmh_focus 		  			true
_bc history_aware_focus           true
_bc remove_disabled_monitors      true
_bc merge_overlapping_monitors    true
_bc pointer_follows_monitor 			true
_bc pointer_modifier mod1
_bc pointer_action1 move
_bc pointer_action2 resize_side
_bc pointer_action3 resize_corner

# Colors
bspc config active_border_color "#928374"
bspc config focused_border_color "#928374"
bspc config normal_border_color "#373d41"
bspc config presel_feedback_color "#373d41"

# Rules

#bspc rule -a firefox -o desktop=1
bspc rule -a firefox desktop='^1' follow=on focus=on
bspc rule -a discord-canary desktop='^2' follow=on focus=on
bspc rule -a kitty desktop='^3' follow=on focus=on
bspc rule -a spacefm desktop='^4' follow=on focus=on
bspc rule -a spotify desktop='^5' follow=on focus=on
bspc rule -a feh state='floating'
bspc rule -a mpv state='floating'
bspc rule -a openssh-askpass state='floating'
bspc rule -a "Iwgtk" state='floating'
bspc rule -a Zathura state='tiled'
bspc rule -a Pavucontrol state='floating'
bspc rule -a flameshot state='floating'
bspc rule -a *:SPLASH state=floating
bspc desktop -f 1

#fallback, if above doesnt work comment/uncomment
#bspc config pointer_modifier mod1
#bspc config pointer_action1 move
#bspc config pointer_action2 resize_side
#bspc config pointer_action3 resize_corner

# INIT-DAEMONS
xsetroot -cursor_name left_ptr &
pscircle  --output=/tmp/bg.png
feh --no-fehbg --bg-fill "/tmp/bg.png"
dunst &
#~/.config/dunst/launchdunst.sh
~/.config/polybar/launch.sh
polybar main
#picom --config $HOME/.config/picom/picom.conf &
picom &
# xcompmgr -cCfF -t -2 -l -2 -r 2.8 -o 0.55 -D 5 &
#~/dotfiles/pscircle/06-output-to-image.sh

#autostart
~/.config/polybar/launch.sh &
~/.config/bspwm/autostart &
