// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.startupRolloutPrefs.doh-rollout.enabled", true);
user_pref("app.normandy.startupRolloutPrefs.doh-rollout.profileCreationThreshold", "1896163212345");
user_pref("app.normandy.startupRolloutPrefs.doh-rollout.provider-steering.enabled", true);
user_pref("app.normandy.startupRolloutPrefs.doh-rollout.provider-steering.provider-list", "[{ \"name\": \"comcast\", \"canonicalName\": \"doh-discovery.xfinity.com\", \"uri\": \"https://doh.xfinity.com/dns-query\" }]");
user_pref("app.normandy.startupRolloutPrefs.network.preload", true);
user_pref("app.normandy.startupRolloutPrefs.print.tab_modal.enabled", true);
user_pref("app.normandy.user_id", "22fac2ac-9dda-4dd4-9f0e-bd5822f6847d");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1611267296);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1611267294);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1611267292);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 104);
user_pref("browser.newtabpage.activity-stream.impressionId", "{af118c13-d599-42f8-9cbf-9fd87ebdaf52}");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "amazon");
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://amazon.com\",\"label\":\"@amazon\",\"searchTopSite\":true}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1611267295238");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1611288895238");
user_pref("browser.search.region", "US");
user_pref("browser.slowStartup.averageTime", 2202);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20210107154745");
user_pref("browser.startup.homepage_override.mstone", "84.0.2");
user_pref("browser.startup.homepage_override.once", "{\"message_id\":\"WNP_MOMENTS_1\",\"url\":\"https://www.mozilla.org/firefox/welcome/1/\",\"expire\":1611872094859}");
user_pref("browser.startup.lastColdStartupCheck", 1611267293);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1611267295550");
user_pref("distribution.archlinux.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "84.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.mode", 2);
user_pref("doh-rollout.self-enabled", true);
user_pref("dom.push.userAgentID", "f2ab36ea80f143beab89d1ff70c4e0c7");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "84.0.2");
user_pref("extensions.lastPlatformVersion", "84.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_picture_in_picture_overrides", true);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"1f503dda-e9d0-47b4-9f0c-2fc74ccbc6e0\",\"formautofill@mozilla.org\":\"38e20af1-c2af-4a96-8f6a-f42815fcbd71\",\"screenshots@mozilla.org\":\"96a05291-690f-41c8-aa94-2d1534c8a69a\",\"webcompat-reporter@mozilla.org\":\"1ceec99b-f071-4605-9fec-78267f44b5a4\",\"webcompat@mozilla.org\":\"baf5a040-89db-4a77-acf4-0795c60a51c3\",\"default-theme@mozilla.org\":\"1bb549ab-dec2-463d-bf51-7bd69a5fc8b0\",\"google@search.mozilla.org\":\"07a68472-47e5-43a6-a46a-a782c6842024\",\"amazondotcom@search.mozilla.org\":\"1ba122b9-a6a0-4c1b-ae96-f6693a7fdd6f\",\"wikipedia@search.mozilla.org\":\"c0b90257-ebd6-45f0-86a7-8a5e44f46fe4\",\"bing@search.mozilla.org\":\"dd269968-6e7b-4f09-9635-cebc703ea3c4\",\"ddg@search.mozilla.org\":\"b9403660-cace-4013-ac1f-b4c8e29efe98\",\"ebay@search.mozilla.org\":\"0db68149-2d04-467f-b3a2-0845657f5960\"}");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "a4183135-02e4-4b78-902d-5b8ce8d37546");
user_pref("security.sandbox.plugin.tempDirSuffix", "4cad4047-f7c4-4386-b243-a6cf2d50922c");
user_pref("toolkit.startup.last_success", 1611267290);
user_pref("toolkit.telemetry.cachedClientID", "7ee99a3b-43c0-4452-9426-9eeec2f81573");
user_pref("toolkit.telemetry.previousBuildID", "20210107154745");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
